### PR TITLE
Upgrade to Agda v2.6.1.

### PR DESCRIPTION
**Pull request by wenkokke**
Upgrade to Agda v2.6.1 and Standard Library v1.3.

I've replaced the data declarations for Gas by record declarations, which solves the issues with the termination checker. Another option is to remove the `gas` wrapper, and use natural numbers directly, but I feel defining Gas as a record is probably preferred.

### CODE REVIEW

**Comment by jsiek** [comment]
Thanks for doing the upgrade to 2.6.1! The record approach for Gas sounds fine to me.

**Comment by wenkokke** [comment]
Unfortunately, it remains to deal gracefully with [the change to the equational reasoning syntax](https://github.com/agda/agda-stdlib/blob/master/CHANGELOG/v1.3.md#changes-to-how-equational-reasoning-is-implemented).

**Comment by wenkokke** [comment]
This should be ready to merge.

**Comment by jsiek** [comment]
It would be nice to get this upgrade sooner than later... I need to upgrade my computer's
installation of Agda to 2.6.1 for other projects. Regarding the equational reasoning syntax,
I propose we do the obvious thing now and replace it with the graceful thing later.

**Comment by wenkokke** [comment]
I've been waiting for @wadler on this, but majority consensus isn't half bad. I'll take care of this later today. Migrating to a new Agda version is unfortunately a bit of a hassle. In the meantime, you can checkout the branch issue468 locally, and test and run on that branch, and switch back to dev before you commit. That's what I've been doing.

**Comment by jsiek** [comment]
> On Jul 19, 2020, at 10:58 AM, Wen Kokke <notifications@github.com> wrote:
> 
> 
> I've been waiting for @wadler <https://github.com/wadler> on this, but majority consensus isn't half bad. I'll take care of this later today. Migrating to a new Agda version is unfortunately a bit of a hassle. In the meantime, you can checkout the branch issue468 locally, and test and run on that branch, and switch back to dev before you commit. That's what I've been doing.
> 
Ok, thanks, that helps!

Cheers,
Jeremy

**Pull request merged**
