### PR TITLE
EPUB output: Populate acknowledgements.md with contributors

### PR DESCRIPTION
**Pull request by mreed20**
See the commit message for more information.

References #480.

## TODO

- [x] bracketed inclusion of `<ul class="list-of-contributors"> ... </ul>`
- [x] deal with `site.contributors`
- [x] include `liquid.lua`

### CODE REVIEW

**Comment by wenkokke** [comment]
Changing the layout by removing the list-of-contributors class isn't an option. What is the HTML generated by Pandoc? Is there a way to get the class back in?

**Comment by wenkokke** [comment]
On second thought: your current approach adds yet another dependency to building the web version of the book (i.e. Pandoc) and it may be a good idea to avoid that. Adding Lustache as a dependency for building the EPUB version may be an acceptable compromise.

**Comment by mreed20** [comment]
> Changing the layout by removing the list-of-contributors class isn't an option. What is the HTML generated by Pandoc? Is there a way to get the class back in?

Got it. I didn't expect to keep that class removed; it was just to temporarily quell the epubcheck warnings. I'll look into ways around that. We can probably bracket the opening and closing `<ul>` tags with a template variable like `isWebsite`, which when defined to a non-null value would include the tags and exclude them otherwise.

> On second thought: your current approach adds yet another dependency to building the web version of the book (i.e. Pandoc) and it may be a good idea to avoid that. Adding Lustache as a dependency for building the EPUB version may be an acceptable compromise.

Wouldn't that still incur an additional dependency for the website generation (i.e., lustache)? Lustache's template syntax is different from the Jekyll template syntax used previously, so users would still need to install lustache to build the website.

**Comment by mreed20** [comment]
Also, in the deleted `acknowledgements.md`, what's the difference between `site.contributors` and `site.extra_contributors`? I didn't see `site.contributors` defined in `_config.yml`.

**Comment by wenkokke** [comment]
> Also, in the deleted `acknowledgements.md`, what's the difference between `site.contributors` and `site.extra_contributors`? I didn't see `site.contributors` defined in `_config.yml`, but I'm wondering if I should include it in the template file.

`site.contributors` is computed from GitHub data and appended to `_config.yaml` for deployed builds only, whereas `site.extra_contributors` is managed manually, and is for folks whose contributions were outside of GitHub or aren't registered by GitHub – due to, e.g., git misconfiguration.

**Comment by wenkokke** [comment]
> > Changing the layout by removing the list-of-contributors class isn't an option. What is the HTML generated by Pandoc? Is there a way to get the class back in?
> 
> Got it. I didn't expect to keep that class removed; it was just to temporarily quell the epubcheck warnings. I'll look into ways around that. We can probably bracket the opening and closing `<ul>` tags with a template variable like `isWebsite`, which when defined to a non-null value would include the tags and exclude them otherwise.
> 
> > On second thought: your current approach adds yet another dependency to building the web version of the book (i.e. Pandoc) and it may be a good idea to avoid that. Adding Lustache as a dependency for building the EPUB version may be an acceptable compromise.
> 
> Wouldn't that still incur an additional dependency for the website generation (i.e., lustache)? Lustache's template syntax is different from the Jekyll template syntax used previously, so users would still need to install lustache to build the website.

Ugh, right... that's... annoying. I wish moustache templating was standardised. The easiest way to proceed is probably with a Ruby script which invokes Liquid, either as a shell script or as a Pandoc filter using [paru](https://heerdebeer.org/Software/markdown/paru/).

**Comment by wenkokke** [comment]
It may be a good idea to translate your Lua code to Ruby... eventually... to reduce the number of scripting language we're depending on. So I'm not opposed to adding the dependency on paru.

**Comment by mreed20** [comment]
> It may be a good idea to translate your Lua code to Ruby... eventually... to reduce the number of scripting language we're depending on. So I'm not opposed to adding the dependency on paru.

Yes, the number of languages is getting out of hand lol.

**Comment by wenkokke** [comment]
Would you be able to translate your Lua scripts? Or should I plan on doing that myself?

**Comment by mreed20** [comment]
> Ugh, right... that's... annoying. I wish moustache templating was standardised. The easiest way to proceed is probably with a Ruby script which invokes Liquid, either as a shell script or as a Pandoc filter using [paru](https://heerdebeer.org/Software/markdown/paru/).

Standard

**Comment by mreed20** [comment]
Woah woops

**Comment by wenkokke** [comment]
> Would you be able to translate your Lua scripts? Or should I plan on doing that myself?

For instance, there's an example here which includes files:
https://heerdebeer.org/Software/markdown/paru/#writing-and-using-pandoc-filters-with-paru#insert-other-pandoc-files

**Comment by mreed20** [comment]
Sorry, wrong button. 

> Would you be able to translate your Lua scripts? Or should I plan on doing that myself?

I don't know ruby, so I'd prefer to avoid that for now. I don't mind learning it though. By the way, are you talking about the `format-acknowledgements` Lua script in particular, or also about the pandoc Lua filters? I ask because while pandoc supports writing filters in any language, their Lua filters are super fast: scroll down to the [end of this section](https://pandoc.org/lua-filters.html#introduction) for a performance comparison.

**Comment by wenkokke** [comment]
Ohh, that's pretty neat, actually! I'm not too worried about the performance penality, since we're unlikely to be running this code very often. I'm more worried about the fact that I don't know Lua, and I'll likely have to maintain and extend this code. The fact that a Lua interpreter ships with Pandoc is reassuring, though.

**Comment by mreed20** [comment]
Good point about the performance penalty---it doesn't matter much. And I completely understand the need to keep code maintainable.

> However, this does make me think... we've been wanting to move over to Hakyll & Pandoc for static site generation for a while now, so maybe we could eventually cut out Ruby altogether.

I'd love to look into this, although I don't know if I should do that before this is merged or after.

**Comment by wenkokke** [comment]
For now, I wouldn't be too grumpy about you just straight-up including [liquid.lua](https://raw.githubusercontent.com/chenxianyu2015/liquid-lua/master/lib/liquid.lua) in the `epub/` directory, and loading it from there.

**Comment by wenkokke** [comment]
> I'd love to look into this, although I don't know if I should do that before this is merged or after.

Yeah, probably after. Mostly, it means I'm not too upset about using Pandoc and some Lua scripts.

**Comment by mreed20** [comment]
@wenkokke Just force pushed the new changes. Check out the commit message for more info. I also just did a fresh build of the website and ebook, and both are looking good.

**Comment by wenkokke** [comment]
I'm getting the following error:
```
Error running filter epub/include-files.lua:
Error during function call: could not read argument 1: Expected an AST element, but could not parse value as such.
stack traceback:
	[C]: in function 'pandoc.utils.stringify'
	epub/include-files.lua:51: in function 'CodeBlock'
make: *** [out/plfa.epub] Error 83
```

**Comment by mreed20** [comment]
Shoot, I couldn't reproduce that on my system when running `make epub` under a fresh install (via luarocks) of all the Lua dependencies and a clean git repository (via `git clean -fdx`).

What version of pandoc are you using? And what's the output of running `luarocks list`?

**Comment by wenkokke** [comment]
Ah, see. I don't have luarocks, which probably means that this is a weird way for lua to tell me that I'm missing dependencies? Did you add instructions on installing the dependencies anywhere?

Mind you, this failure occurs while building the EPUB via `make`, not via `make epub`... I'm not sure if it should be included in the regular `make`?

**Comment by mreed20** [comment]
> Ah, see. I don't have luarocks, which probably means that this is a weird way for lua to tell me that I'm missing dependencies? Did you add instructions on installing the dependencies anywhere?

Unfortunately, I think you're right. And good point: I'll add instructions to the README.

> Mind you, this failure occurs while building the EPUB via `make`, not via `make epub`... I'm not sure if it should be included in the regular `make`?

Sure, I can remove `epub` from the `all` Makefile target. I have no strong preference either way since most users will likely download the EPUB from Github, and not build it themselves.

**Comment by mreed20** [comment]
Just pushed changes addressing your feedback. Lemme know how the instructions are for you.

**Comment by wenkokke** [comment]
While I now have luarocks and the required packages, the error remains unchanged. I'm running Pandoc version 2.9.2.1.

**Comment by mreed20** [comment]
What OS (+version) and Lua version are you using? I'd like to spin up a VM and try to reproduce this

**Comment by wenkokke** [comment]
> What OS (+version) and Lua version are you using? I'd like to spin up a VM and try to reproduce this

MacOS 10.14 and Lua 5.3.5.

**Comment by mreed20** [comment]
> MacOS 10.14 and Lua 5.3.5.

Same, but I'm on macOS 10.15.5. Could this be related to my force pushes?

**Comment by wenkokke** [comment]
Maybe? Could you try building a fresh clone of the pull request?

**Comment by mreed20** [comment]
aha! I reproduced it. Good call on the fresh clone. I also nuked my `~/.local/` directory and reinstalled Lua and Luarocks, which might have been related.

Will look into it now.

**Comment by mreed20** [comment]
Check your `src/plfa/acknowledgements_epub.md`, which should be either
a) not have a definition for `title` in the metadata block (at the top of the file), or
b) be an empty file.

Either one of those possibilities triggered the same crash for me at `epub/include-files.lua:51`.

Alternatively, some other markdown file that is part of your build lacks the `title` attribute.

**Comment by mreed20** [comment]
Just beefed up the error checking on `run-liquid.lua`, and I'm not experiencing the error on my end. Try doing a `make epub` from a fresh clone.

**Comment by wenkokke** [comment]
It works now! I am still getting the error on nested p's, but I'm assuming that's due to the dedication.

**Comment by wenkokke** [comment]
Thanks for all your work on this!

**Comment by mreed20** [comment]
I should be thanking you, you've been committing nonstop today! I feel a little bad about all the Lua trouble I caused you with Travis; I'm glad the script is now in Ruby.

**Pull request merged**
