### PR TITLE
Close quotation mark

### PR DESCRIPTION
**Pull request by OlingCat**

### CODE REVIEW

**Comment by wenkokke** [comment]
Thanks, @OlingCat!

**Comment by OlingCat** [comment]
@wenkokke  Sorry, I just noticed this fix was wrong. It's from another place as a qoute. can you revert that?

**Comment by wenkokke** [comment]
Ah, I merged over-eagerly. Thanks for spotting that! We should probably fix the quotation marks so in doesn't have nested double quotes.

**Review by wadler — COMMENTED** [review]
Thanks! But isn't there an extra close quote at the end of the paragraph which needs to go?

**Pull request merged**
