### PR TITLE
Remove the unused Eq in Relations

### PR DESCRIPTION
**Pull request by favonia**

### CODE REVIEW

**Comment by favonia** [comment]
Hmm. Maybe `Eq` was used in the intended solutions? I did not check those.

**Comment by wenkokke** [comment]
We likely did this to keep the line lengths down.

**Comment by favonia** [comment]
> We likely did this to keep the line lengths down.

How about the following, then?
```agda
open import Relation.Binary.PropositionalEquality
   using (_≡_; refl; cong)
```

**Comment by wenkokke** [comment]
That would work, but why would it be preferable?

**Comment by favonia** [comment]
> That would work, but why would it be preferable?

Because `Eq` is unused. However, I do not have a strong opinion on this---this PR was meant to be a small style clean-up only.

**Pull request closed without merging**
