### PR TITLE
fix README.md link to EPUB e-book

### PR DESCRIPTION
**Pull request by yeradis**
Simple update to fix a broken link to the EPUB e-book

### CODE REVIEW

**Review by wadler — CHANGES_REQUESTED** [review]
Thanks! The old link is clearly wrong. There are also problems with the new link, for instance no chapter headings appear in the epub. I have an older version without these errors. Wen, any idea what went wrong?

**Comment by yeradis** [comment]
@wadler Hi

Don't really know what went wrong, arrived here looking for an offline version of the ebook and then found the link was broken

So, first time here,

But just downloaded the repo to build everything from scratch including the epub version of the ebook to see if there are some warning or errors

The correct version you have is available at some place so i can compare? 

Regards

**Comment by wadler** [comment]
Wen should have an up-to-date copy of the correct ebook for comparison. Wen, can you supply this to Yeradis?

**Comment by yeradis** [comment]
Hello again

I tried to look into this in multiple ways but got stuck cause i'm not able to run the full process on MacOS BigSur,
something have change on this OS version making compile process to fail, this seems to be fixed on recent GHC versions but not on the version that this projects need 
as a reference https://gitlab.haskell.org/ghc/ghc/-/issues/19037

Sorry but with my current knowledge about the toolchain i can not go deeper

Regards

**Comment by wenkokke** [comment]
Unfortunately, EPUB generation is broken at the moment :( If someone has the expertise with Pandoc to help us fix it that would be greatly appreciated!

**Pull request merged**
