### PR TITLE
Mention jekyll as a build dependency

### PR DESCRIPTION
**Pull request by ywata**
During #213 investigation, I noticed installing jekyll is needed to build the book. It's better to mention it in README file.

### CODE REVIEW

**Comment by wenkokke** [comment]
Jekyll is used to build and host the book, but it is automatically installed using bundler.

**Comment by ywata** [comment]
Ah. I see. In my case,I had to install it explicitly. I have one possible cause of this and I'll check it.

**Comment by ywata** [comment]
@wenkokke 

I checked the possible issue. It was not cause of my case. 
After I uninstall everything bundle related, I tried to run make again. 
It gave me'
```make
ruby -S bundle exec jekyll build
bundler: command not found: jekyll
Install missing gem executables with `bundle install`
make: *** [build] Error 127
```

I read Makefile and I guess you expect us to run make macos-setup before running make build on MacOS.

**Comment by wenkokke** [comment]
That's a good point, there should be a general setup command. Thanks.

**Comment by ywata** [comment]
As https://jekyllrb.com/ says,
installing bundler and jekyll is possible with the command below:
`gem install bundler jekyll`
This was easy for me.

**Comment by wenkokke** [comment]
The correct way to install all the ruby dependencies is to call:
```bash
gem install bundler
bundle install
```

**Pull request closed without merging**
