### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by dpl0a**
Added course from university of Padova

### CODE REVIEW

**Review by wenkokke — APPROVED** [review]

**Comment by wadler** [comment]
Excellent, thank you! Will the course also run this year?

**Comment by dpl0a** [comment]
Technically yes but i'm not sure, since it all depends on how many people actually passed the course. I'll ask Prof. Maietti about that.

P.S. the course also ran in 2020

**Comment by wadler** [comment]
I thought you added the instance for 2020? If the course also ran in other years, please add those too!

**Comment by dpl0a** [comment]
Sorry, I made a mess.
I meant the 2019-2020 _academic year_. The course also ran in the 2020-2021 academic year and i'm not sure if it'll run in 2021-2022.

**Pull request merged**
