### PR TITLE
Minor additional update to tspl-2023-10-19

### PR DESCRIPTION
**Pull request by wadler**

### CODE REVIEW

**Comment by wenkokke** [comment]
@wadler I think you've got a double closing `</td>`: https://github.com/plfa/plfa.github.io/blob/f5f188e7a49dd31002da2fbf81462dc3b63ffae6/courses/TSPL/2023/tspl.md?plain=1#L79

**Comment by wadler** [comment]
I've edited to eliminate the extra </td>. Is it ok to accept now?

(For some reason I didn't see your previous message, and only discovered it when I went to check why my pull request had not deployed.)

**Comment by wenkokke** [comment]
You've got another:
https://github.com/plfa/plfa.github.io/blob/0b43e1ea7af066a4d479325e94028de927fe8cd0/courses/TSPL/2023/tspl.md?plain=1#L70

Probably best to double check the rest as well.

**Comment by wadler** [comment]
Double checked. It looks fine now.

**Comment by wenkokke** [comment]
I don't think you've pushed any new changes?

**Comment by wadler** [comment]
Changes should be committed now. I made them direct on github, so I presume push is not relevant. Hope it's ok this time!

**Pull request merged**
