### PR TITLE
Add missing symbols in Fonts.lagda.md

### PR DESCRIPTION
**Pull request by Altariarite**
I found these symbols that should be included in Fonts.lagda.md
```
〕 U+3015
〔 U+3014
⨟ U+2A1F
(part2/Substitution)

ℰ U+2130
(part3/Adequacy)
ℱ U+2131
(part3/Compositional)
⨆ U+2A06
(part3/Denotational)
```

### CODE REVIEW

**Review by wadler — CHANGES_REQUESTED** [review]
I don't understand the reason for these changes. The comment on the pull request only mentioned fonts.

**Review by wadler — CHANGES_REQUESTED** [review]
I don't understand the reason for these changes. The comment on the pull request only mentioned fonts.

**Comment by wadler** [comment]
Change to fonts needs to be put in a separate commit.

**Comment by Altariarite** [comment]
I cleaned up the commit history and recreated a pull request in https://github.com/plfa/plfa.github.io/pull/567

**Pull request closed without merging**
