### PR TITLE
Add Shulman to users list

### PR DESCRIPTION
**Pull request by mikeshulman**

### CODE REVIEW

**Comment by wadler** [comment]
Thanks! Can you please at least add a link to yourself, if not to your course?

**Comment by mikeshulman** [comment]
There's no course website because I didn't teach a course, just worked through it with three summer research students.  Favonia and John Leo don't have links and all the other links are to course websites.  Are you saying you want me to link my name to my personal homepage?

**Comment by wenkokke** [comment]
I would prefer that readers do not get confused between course pages and home pages, so I have merged your pull request as is while @wadler and I discuss how to allow people to link their homepage in a way that is visually distinct.

**Comment by wadler** [comment]
Mike, Is there any way you could create a short webpage to give a brief description of how you used PLFA, and link to that?

**Comment by mikeshulman** [comment]
Maybe after the summer is over, my students and I can make a short web page
together summarizing what we did.

**Pull request merged**
