### PR TITLE
add another missing import

### PR DESCRIPTION
**Pull request by tammela**

### CODE REVIEW

**Comment by wenkokke** [comment]
Could you clarify in what sense these are missing?

**Comment by tammela** [comment]
> Could you clarify in what sense these are missing?
Missing `≲` definition for exercise "`—↠≲—↠′`" (https://github.com/plfa/plfa.github.io/pull/271)
Missing `×` definition for exercise "``Context-≃`"

**Comment by wenkokke** [comment]
I don't think we should add imports for constructs that are needed only during exercises. You, @wadler?

**Comment by wadler** [comment]
@tammela: Good catch, thank you. @wenkokke: Good question. I lean toward leaving it to the student to add such imports when they are required. @tammela, let us know if you think that puts too big a burden on the students.

**Comment by tammela** [comment]
@wenkokke @wadler seems reasonable to let the students import whatever they need.
Thanks for the clarification

**Pull request closed without merging**
