### PR TITLE
Fix #987

### PR DESCRIPTION
**Pull request by wenkokke**

### CODE REVIEW

**Review by wadler — COMMENTED** [review]
What is the reason for this change?
Plus: it avoids the scary `--recurse-submodules` and `--shallow submodules` commands.
Minus: I now need to cut-and-paste two commands instead of one.

**Comment by wenkokke** [comment]
That's the proposed fix for the CVE noted in #987.

**Comment by wenkokke** [comment]
The issue is with `--recurse-submodules` and the suggestion is to avoid it.

**Comment by wadler** [comment]
Thanks. I followed the #987 link after I wrote my message, after which I wrote a second message beginning "Doh". Somehow the second message wasn't posted. Yes, I agree with the change.

**Pull request merged**
