### PR TITLE
more symbols on the font test page. removed somw symbols not used in book.

### PR DESCRIPTION
**Pull request by Cubesoup**

### CODE REVIEW

**Comment by Cubesoup** [comment]
The extra \rho / \Rho thing was a mistake -- good catch! 

The extra lambda symbol was present further down the list, but I've moved it next to the normal lambda (it's occurrence as four symbols, not as part of the alphabet). 

I've moved the symbols that are egregiously non-monospaced (on my screen, on Github) to the section at the bottom.

**Comment by wenkokke** [comment]
@Cubesoup did you check whether they ligned up (or not) on the font we use on the webpage, or using the font you use on your editor/system? This looks good to me, btw.

**Comment by Cubesoup** [comment]
I checked with my editor (which uses a bunch of different fonts at the moment), and with the Github font. I can't currently build the book locally, so it would be difficult for me to check with the webpage font.

In any case, I think the font test page is more aspirational than anything right now.

**Comment by wenkokke** [comment]
Point taken.

**Comment by Cubesoup** [comment]
Done.

**Comment by Cubesoup** [comment]
I have added "fake" long arrows to the font test page (em-dash followed by an arrow symbol).

**Pull request merged**
