### PR TITLE
Lambda: removes a superfluous back-tick in a typing judgment

### PR DESCRIPTION
**Pull request by mdimjasevic**
In the chapter on lambda calculus, this patch remove s a superfluous back-tick in a typing judgment.

### CODE REVIEW

**Comment by wenkokke** [comment]
Found another one?

**Comment by mdimjasevic** [comment]
My apologies! You were so fast to merge this that I thought somehow my pull request mysteriously disappeared!

**Comment by wenkokke** [comment]
Welp, let's see what happens when I merge a pull request twice.

**Comment by wadler** [comment]
Thank you for your dedication!

**Comment by mdimjasevic** [comment]
@wadler , you are most welcome!

Thank you for writing this book and making it available under a free culture license! That's why I'm glad to contribute with these small changes. It's been a great learning experience for me to work through the book. My hope is to eventually work on a dependent type theory project, and I'm expecting that this book combined with your work on propositions as types will be very useful for it!

**Pull request merged**
