### PR TITLE
Add EPUB creation to the build

### LINKED ISSUE #112: Release of the "mobile" versions of the book (epub/mobi)
It would be nice to release book in epub (and/or mobi) format

### PR DESCRIPTION
**Pull request by mreed20**
Hi!

This pull request adds preliminary support for creating an EPUB3 version of PLFA. This is very much a rough draft, as I'd like to get some feedback before doing the rest. Things mostly work, although there are a few broken aspects. See the commit message for more info.

Closes #112.

p.s.: Thank you for writing this fantastic book, and for making it free.

### CODE REVIEW

**Comment by wenkokke** [comment]
Thanks, @mreed20! I've just checked out your code. It works, and it doesn't look half-bad!

There's a couple of small changes that should be made:

- The entry in the makefile should be `out/plfa.epub` and list all the lua code and the markdown dependencies. The entry `epub` should redirect to this.
- I see that you're embedding DejaVuSansMono, why aren't you embedding mononoki?
- The cleanup for the epub file should be under the `clobber` task, not under the `clean` task.
- The epub creation should be integrated into the Travis CI test suite. I have no idea how to test if the links in the epub work, or how to see if the epub is well-formatted, but for now we can make do with the call to pandoc succeeding and an epub file being generated.

**Comment by mreed20** [comment]
> Thank you! How would we go about testing what you've done? I'm going to leave it to Wen to approve this pull, as she knows much more about the mechanics.

@wadler I plan on integrating [epubcheck](https://github.com/w3c/epubcheck) into Travis CI to get automated EPUB validation. Beyond that, I have not looked much into testing... beyond reading it on my 10 year old ereader 😄 

> There's a couple of small changes that should be made:

@wenkokke Thanks for the review! I just made all your changes, plus a few more (embedded fonts should work now, probably). Travis doesn't seem to be running on this pull request, however, so I wasn't able to test the Travis changes yet. I also haven't worked with Travis before, so I have no clue if my Travis changes are correct.

**Comment by wenkokke** [comment]
Thanks for the changes, @mreed20! I'm expecting that the way you're downloading Pandoc on Travis doesn't work, but I'll take the Travis integration from here!

**Comment by wenkokke** [comment]
I'm gonna merge this pull request - unfortunately, there's no *easy* way to test Travis on pull requests without compiling Agda from scratch.

**Comment by wenkokke** [comment]
Yeah, the `dpkg` command fails on Travis:
```
dpkg -i /home/travis/pandoc.deb
dpkg: error: requested operation requires superuser privilege
Makefile:173: recipe for target '/usr/bin/pandoc' failed
make: *** [/usr/bin/pandoc] Error 2
The command "make travis-setup" failed and exited with 2 during .
```

**Comment by wenkokke** [comment]
Okay, I've sorted that. I'm working on the integration of `epubcheck`, but there's MANY errors still to fix. I've opened issue #480 for these errors. Your help would be greatly appreciated, @mreed20! Once those errors are fixed, we can make checking the epub part of testing.

**Comment by mreed20** [comment]
Thanks for getting this integrated so quickly Wen! And I'd love to help, I'll try to squeeze in some time this week for that.

**Pull request merged**
